# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

import sys, os
from abaqusGui import getAFXApp

# rsg
user = os.environ.get('USERNAME') or os.environ.get('USER')
plugin_name = 'VAB_oblique_v10'
rsg_tmp_dir = os.path.join(
    os.path.expanduser("~"),
    'abaqus_plugins', '_rsgTmpDir', plugin_name
)

if rsg_tmp_dir not in sys.path:
    sys.path.insert(0, rsg_tmp_dir)

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT

execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='VAB_oblique_v10', kernelModule='VAB_oblique_v10', kernelFunction='VAB_oblique', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgIcon(p='DialogBox', fileName=r'GG.png')
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='parameter', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=21, labelText='angle', keyword='angle', default='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=24, labelText='Vs', keyword='cs', default='')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=24, labelText='vv', keyword='vv', default='')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=20, labelText='density', keyword='density', default='')

dialogBox.show()